"""STEP 6 — Worker protocol: run(task) -> result. FakeWorker is the default mock."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol


@dataclass
class WorkerTask:
    run_id: str
    worktree: str
    artifact_paths: dict[str, str]
    instruction: str


@dataclass
class WorkerResult:
    summary: str
    changed_files: list[str]


class Worker(Protocol):
    name: str

    def run(self, task: WorkerTask) -> WorkerResult: ...


class FakeWorker:
    """Deterministic mock — writes a tiny fix file into the worktree."""

    name = "fake"

    def run(self, task: WorkerTask) -> WorkerResult:
        fix = Path(task.worktree) / "fix_stub.py"
        fix.write_text(
            "# auto-generated by FakeWorker\n"
            f"# run_id={task.run_id}\n"
            "def current_user():\n"
            "    return {}\n",
            encoding="utf-8",
        )
        return WorkerResult(
            summary=(
                f"FakeWorker diagnosed issue using {len(task.artifact_paths)} artifacts; "
                "wrote fix_stub.py (null-guard for current_user)."
            ),
            changed_files=["fix_stub.py"],
        )


class ClaudeWorker:
    """Stub for a real LLM worker — not used in tests; swap in via build_graph."""

    name = "claude"

    def run(self, task: WorkerTask) -> WorkerResult:
        raise NotImplementedError("ClaudeWorker is a stub — use FakeWorker in this tutorial")
