-- =============================================================================
-- SEC filings RAG store
-- Postgres >= 15 + pgvector >= 0.7.0 (required for halfvec)
--
-- Embeddings : OpenAI text-embedding-3-large  →  3072 dimensions
-- Storage    : halfvec(3072) — 16-bit, halves storage vs float4, HNSW-indexable
--              up to 4 000 dimensions (plain vector is capped at 2 000 for HNSW)
-- Run once   : psql $DATABASE_URL -f schema.sql
-- Idempotent : all statements use IF NOT EXISTS — safe to re-run
-- =============================================================================

-- pgvector extension  --------------------------------------------------------
-- Installs the vector / halfvec types, operators, and index access methods.
-- Must be run in the target database (sec_rag), not in postgres.
CREATE EXTENSION IF NOT EXISTS vector;

-- =============================================================================
-- documents — one row per SEC filing
--
-- id           UUID4 generated by chunker.py. Native UUID type: 16 bytes,
--              format-validated, no collision risk, standard across tools.
-- url          Canonical EDGAR archive URL — the natural unique key.
--              Used as the ON CONFLICT target in embed_load.py so that
--              re-ingesting the same filing updates metadata in-place.
-- cik          SEC Central Index Key — permanent, never recycled.
--              More reliable than ticker for identity.
-- fiscal_period Period the filing *covers* (e.g. FY2023), distinct from
--              filing_date (the date it was submitted to the SEC).
-- =============================================================================
CREATE TABLE IF NOT EXISTS documents (
    id            UUID        PRIMARY KEY,         -- uuid4 from chunker.py

    cik           TEXT        NOT NULL,           -- e.g. "0000320193"
    ticker        TEXT,                           -- e.g. "AAPL"
    company       TEXT        NOT NULL,           -- e.g. "Apple Inc."
    form_type     TEXT        NOT NULL,           -- e.g. "10-K"
    filing_date   DATE,                           -- date filed with the SEC
    fiscal_period TEXT,                           -- period covered, e.g. "FY2023"
    url           TEXT        NOT NULL UNIQUE     -- EDGAR HTML archive URL
);

-- B-tree indexes for the metadata filters used in queries.py
CREATE INDEX IF NOT EXISTS documents_cik_idx        ON documents (cik);
CREATE INDEX IF NOT EXISTS documents_ticker_idx     ON documents (ticker);
CREATE INDEX IF NOT EXISTS documents_form_idx       ON documents (form_type);
CREATE INDEX IF NOT EXISTS documents_period_idx     ON documents (fiscal_period);
-- Composite: the most common query pattern is (ticker, form_type)
CREATE INDEX IF NOT EXISTS documents_ticker_form_idx ON documents (ticker, form_type);

-- =============================================================================
-- chunks — many rows per filing
--
-- id           UUID4 generated by chunker.py per chunk.
-- document_id  FK to documents.id — CASCADE DELETE keeps the two tables in sync
--              when a document is removed.
-- section      Heading path from Docling, e.g. "PART I > Item 1A. Risk Factors".
--              NULL for cover-page / front-matter chunks.
-- chunk_index  Ordinal position within the filing (0-based). Preserved for
--              reading-order reassembly and neighbour-context expansion.
-- content      The contextualized chunk text passed to text-embedding-3-large.
--              Heading path is prepended by chunker.contextualize().
-- embedding    halfvec(3072): half-precision 3072-dim vector.
--              halfvec uses 2 bytes per dimension (vs 4 for float4 / vector),
--              halving storage while keeping recall negligibly close to full
--              precision. Required to build an HNSW index above 2 000 dims.
-- tsv          Postgres full-text search vector, auto-maintained by Postgres.
--              GENERATED ALWAYS AS STORED — never written by the application.
-- =============================================================================
CREATE TABLE IF NOT EXISTS chunks (
    id            UUID    PRIMARY KEY,
    document_id   UUID    NOT NULL
                      REFERENCES documents (id) ON DELETE CASCADE,

    section       TEXT,
    chunk_index   INT     NOT NULL,
    content       TEXT    NOT NULL,
    embedding     halfvec(3072),
    tsv           tsvector
                      GENERATED ALWAYS AS (to_tsvector('english', content)) STORED
);

-- FK index — speeds up JOIN documents d ON d.id = c.document_id
CREATE INDEX IF NOT EXISTS chunks_document_id_idx
    ON chunks (document_id);

-- GIN index for full-text search (tsv @@ websearch_to_tsquery(...))
CREATE INDEX IF NOT EXISTS chunks_tsv_idx
    ON chunks USING gin (tsv);

-- HNSW vector index for approximate nearest-neighbour search
-- Operator class halfvec_cosine_ops  →  cosine distance operator <=>
-- MUST match the operator used in queries.py (c.embedding <=> %(query)s)
-- If they differ, Postgres silently falls back to a sequential scan.
--
-- Tuning knobs (can be changed with REINDEX):
--   m                 graph connectivity; higher = better recall, more memory
--                     default 16 is a good balance for most workloads
--   ef_construction   candidate list size during build; higher = better recall
--                     at the cost of longer index build time; 64 is the default
CREATE INDEX IF NOT EXISTS chunks_embedding_idx
    ON chunks USING hnsw (embedding halfvec_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- =============================================================================
-- Quick-verify snippet (run after applying the schema):
--
--   SELECT extname, extversion
--   FROM pg_extension WHERE extname = 'vector';
--
--   SELECT table_name, column_name, data_type
--   FROM information_schema.columns
--   WHERE table_name IN ('documents','chunks')
--   ORDER BY table_name, ordinal_position;
--
--   SELECT indexname, indexdef
--   FROM pg_indexes
--   WHERE tablename IN ('documents','chunks')
--   ORDER BY tablename, indexname;
-- =============================================================================